demoapp.name=Demo App
demoapp.version=1

spring.application.name=demo
server.port=8081
spring.datasource.url=jdbc:postgresql://db:5432/mydb
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
